### ISSUE TITLE
Replace repeated .layout-narrow CSS with variables

### ISSUE THREAD

**Issue by twm** [twm/yarrharr#148]
As begun in #145, replace blocks like this:

```css
.layout-narrow .list-article-inner {
    max-width: @narrow_width;
    margin: 0 auto;
}
```

With variables:

```css
.list-article-inner {
    max-width: var(--layout-max-width);
    margin: 0 auto;
}
```
